dbt_practice:
  target: prod
  outputs:
    dev:
      type: bigquery
      method: service-account
      project: dbt-practice-355719
      threads: 4
      keyfile: /secrets/dbt-service-account
      timeout_seconds: 300
      priority: interactive
      retries: 1
    
    prod:
      type: bigquery
      method: service-account
      project: dbt-practice-355719
      threads: 4
      keyfile: /secrets/dbt-service-account
      timeout_seconds: 300
      priority: interactive
      retries: 1