dbt_practice:
  target: prod
  outputs:
    dev:
      type: bigquery
      method: service-account
      project: dbt-practice-dev
      dataset: dev
      threads: 4
      keyfile: dbt-practice-dev-acbb32f43642.json
      timeout_seconds: 300
      priority: interactive
      retries: 1
    
    prod:
      type: bigquery
      method: service-account
      project: dbt-practice-355719
      dataset: prod
      threads: 4
      keyfile: /secrets/dbt-service-account
      timeout_seconds: 300
      priority: interactive
      retries: 1